In [1]:
import numpy as np

In [2]:
# 1 d array

In [11]:
a=np.array([1,2,3,4,5,6,7,8,'manish'])

In [12]:
a

array(['1', '2', '3', '4', '5', '6', '7', '8', 'manish'], dtype='<U11')

In [13]:
print(a)

['1' '2' '3' '4' '5' '6' '7' '8' 'manish']


In [14]:
a.ndim

1

In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
a.dtype

dtype('<U11')

In [17]:
a.size

9

In [18]:
len(a)

9

In [19]:
a.shape

(9,)

In [21]:
# arange-----> range
# arange(start,end,step)

In [22]:
x=np.arange(20)

In [23]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
x.ndim

1

In [25]:
y=np.arange(10,30,2)

In [26]:
y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
# selection of 1-d array

In [28]:
y[0]

10

In [29]:
y[1]

12

In [32]:
y[:5]

array([10, 12, 14, 16, 18])

In [31]:
y[2:9:2]

array([14, 18, 22, 26])

In [33]:
# 2-d ----> shape (row,col) ----> row*col==len(element)

In [34]:
#20-------> 5*4,4*5,10*2,2*10
#100------> (10*10),(20*5),(25*4),(50,2)

In [38]:
s=np.arange(80).reshape(40,2)  # (row,col) ---> row =15, col=4

In [39]:
print(s)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]
 [50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]
 [66 67]
 [68 69]
 [70 71]
 [72 73]
 [74 75]
 [76 77]
 [78 79]]


In [40]:
s.ndim

2

In [43]:
m=np.arange(20,60,2).reshape(5,4)

In [44]:
m

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [45]:
w=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
w.ndim

2

In [48]:
w.shape

(3, 3)

In [49]:
# 3-d array ----> collection of 2d array

In [50]:
r=np.arange(100).reshape(5,4,5) # (number of 2d , row(2d), col(2d))

In [51]:
r

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [55]:
s=np.arange(60).reshape(3,4,5)

In [53]:
s

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [56]:
s.ndim

3

In [57]:
# selection  2d and 3d 

array(['1', '2', '3', '4', '5', '6', '7', '8', 'manish'], dtype='<U11')

In [59]:
m

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [60]:
#30 ,32
#38 ,40

In [64]:
m[3:,1:3]# m[row(start:end),col(start:end)]

array([[46, 48],
       [54, 56]])