In [1]:
# Arithmatic Operations 

In [2]:
import numpy as np 

In [3]:
a=np.arange(12).reshape(3,4)
b=np.arange(30,42).reshape(3,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [6]:
l=[1,2,3]
l1=[4,5,6]

In [7]:
l-l1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [11]:
b-a

array([[30, 30, 30, 30],
       [30, 30, 30, 30],
       [30, 30, 30, 30]])

In [12]:
np.subtract(b,a)

array([[30, 30, 30, 30],
       [30, 30, 30, 30],
       [30, 30, 30, 30]])

In [13]:
b-5

array([[25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [14]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [15]:
a+b

array([[30, 32, 34, 36],
       [38, 40, 42, 44],
       [46, 48, 50, 52]])

In [16]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [17]:
np.add(a,20)

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a/b

array([[0.        , 0.03225806, 0.0625    , 0.09090909],
       [0.11764706, 0.14285714, 0.16666667, 0.18918919],
       [0.21052632, 0.23076923, 0.25      , 0.26829268]])

In [20]:
b/a

C:\Users\rmani\AppData\Local\Temp/ipykernel_8720/2243761560.py:1: RuntimeWarning: divide by zero encountered in true_divide
  b/a


array([[        inf, 31.        , 16.        , 11.        ],
       [ 8.5       ,  7.        ,  6.        ,  5.28571429],
       [ 4.75      ,  4.33333333,  4.        ,  3.72727273]])

In [22]:
np.divide(a,5)

array([[0. , 0.2, 0.4, 0.6],
       [0.8, 1. , 1.2, 1.4],
       [1.6, 1.8, 2. , 2.2]])

In [23]:
a/5

array([[0. , 0.2, 0.4, 0.6],
       [0.8, 1. , 1.2, 1.4],
       [1.6, 1.8, 2. , 2.2]])

In [24]:
a*b

array([[  0,  31,  64,  99],
       [136, 175, 216, 259],
       [304, 351, 400, 451]])

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [27]:
np.multiply(a,b)

array([[  0,  31,  64,  99],
       [136, 175, 216, 259],
       [304, 351, 400, 451]])

In [28]:
m=np.arange(9).reshape(3,3)
n=np.arange(9,18).reshape(3,3)

In [29]:
m   # 0*9+1*12+2*15   =42

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
n

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [31]:
m@n

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [32]:
m.dot(n)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [33]:
np.sqrt(b)

array([[5.47722558, 5.56776436, 5.65685425, 5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253],
       [6.164414  , 6.244998  , 6.32455532, 6.40312424]])

In [34]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [35]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
4*4*4*4

256

In [39]:
np.exp?

In [40]:
np.exp(5)

148.4131591025766

In [42]:
5*5*5*5

625

In [43]:
5**3

125

In [44]:
np.log(5)

1.6094379124341003

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.exp(m)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [50]:
np.log(5)

1.6094379124341003

In [53]:
np.exp(1)

2.718281828459045

In [52]:
np.exp?

In [54]:
e=2.718281828459045

In [57]:
1+4+8+(64/6)+((4**4)/24)

34.33333333333333

In [58]:
np.exp(4)

54.598150033144236

In [59]:
2.718281828459045**4

54.59815003314423

In [60]:
2.718281828459045**3

20.085536923187664

In [61]:
np.exp(3)

20.085536923187668

In [62]:
#exp(x)==e**x

In [63]:
np.sin(90)

0.8939966636005579

In [64]:
np.sin(45)

0.8509035245341184

In [74]:
r=90*np.pi/180

In [75]:
r

1.5707963267948966

In [76]:
np.sin(r)

1.0

In [82]:
t=np.deg2rad(0)

In [79]:
np.sin(t)

1.0

In [80]:
print(t)

1.5707963267948966


In [83]:
np.cos(t)

1.0

In [84]:
q=np.arange(0,361,15)

In [85]:
q

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360])

In [86]:
rad=np.deg2rad(q)

In [87]:
rad

array([0.        , 0.26179939, 0.52359878, 0.78539816, 1.04719755,
       1.30899694, 1.57079633, 1.83259571, 2.0943951 , 2.35619449,
       2.61799388, 2.87979327, 3.14159265, 3.40339204, 3.66519143,
       3.92699082, 4.1887902 , 4.45058959, 4.71238898, 4.97418837,
       5.23598776, 5.49778714, 5.75958653, 6.02138592, 6.28318531])

In [88]:
np.sin(rad)

array([ 0.00000000e+00,  2.58819045e-01,  5.00000000e-01,  7.07106781e-01,
        8.66025404e-01,  9.65925826e-01,  1.00000000e+00,  9.65925826e-01,
        8.66025404e-01,  7.07106781e-01,  5.00000000e-01,  2.58819045e-01,
        1.22464680e-16, -2.58819045e-01, -5.00000000e-01, -7.07106781e-01,
       -8.66025404e-01, -9.65925826e-01, -1.00000000e+00, -9.65925826e-01,
       -8.66025404e-01, -7.07106781e-01, -5.00000000e-01, -2.58819045e-01,
       -2.44929360e-16])

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
m.dot(n)   # dot product

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [91]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [94]:
n@m

array([[ 96, 126, 156],
       [123, 162, 201],
       [150, 198, 246]])