In [1]:
import numpy as np

In [36]:
a=np.arange(16).reshape(4,4)
b=np.arange(0,32,2).reshape(4,4)

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [9]:
a==b

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [10]:
b<5

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [12]:
b>5

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
#aggregate

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a.sum()

120

In [16]:
a.min()

0

In [17]:
a.max()

15

In [20]:
a.max(axis=1)  # axis==0 column wise   or axis=1 row wise

array([ 3,  7, 11, 15])

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [25]:
a.mean()

7.5

In [27]:
np.median(a)

7.5

In [28]:
np.std(a)

4.6097722286464435

In [29]:
np.var(a)

21.25

In [30]:
a=[1,2,3,4,5,6]

In [31]:
4.6097722286464435**2

21.25

In [32]:
a

[1, 2, 3, 4, 5, 6]

In [35]:
b[0].sum()

12

In [37]:
a[0].sum()

6

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [40]:
w=b

In [41]:
w

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [61]:
b[0][1]=20

In [62]:
b

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [63]:
w

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [57]:
w[0:2]

array([[10,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [60]:
b[1][2]+b[]

30

In [64]:
r=b.copy()

In [65]:
r

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [66]:
b

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [69]:
r[0][2]=40

In [70]:
r

array([[10, 20, 40,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [71]:
b

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [80]:
random=np.random.randint(10,50,20).reshape(5,4)

In [81]:
random

array([[40, 16, 37, 34],
       [42, 12, 31, 13],
       [10, 46, 39, 23],
       [23, 24, 32, 17],
       [26, 10, 34, 39]])

In [78]:
random.sort(axis=0)

In [79]:
random

array([[11, 17, 21, 24],
       [17, 19, 24, 35],
       [22, 25, 29, 44],
       [28, 35, 39, 45],
       [32, 38, 44, 49]])

In [82]:
random

array([[40, 16, 37, 34],
       [42, 12, 31, 13],
       [10, 46, 39, 23],
       [23, 24, 32, 17],
       [26, 10, 34, 39]])

In [83]:
random>30

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [84]:
random[random>30]

array([40, 37, 34, 42, 31, 46, 39, 32, 34, 39])

In [85]:
w

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [86]:
w.T   # Transposing array row to column and column to row

array([[10,  8, 16, 24],
       [20, 10, 18, 26],
       [ 4, 12, 20, 28],
       [ 6, 14, 22, 30]])

In [87]:
np.transpose(w)

array([[10,  8, 16, 24],
       [20, 10, 18, 26],
       [ 4, 12, 20, 28],
       [ 6, 14, 22, 30]])

In [89]:
w.ravel()

array([10, 20,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [90]:
w

array([[10, 20,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [92]:
r=np.random.randint(10,50,24).reshape(6,4)

In [93]:
r

array([[41, 30, 14, 16],
       [31, 12, 30, 20],
       [26, 29, 47, 14],
       [15, 27, 15, 34],
       [40, 36, 19, 35],
       [32, 33, 20, 33]])

In [94]:
r.resize((8,3))

In [95]:
r

array([[41, 30, 14],
       [16, 31, 12],
       [30, 20, 26],
       [29, 47, 14],
       [15, 27, 15],
       [34, 40, 36],
       [19, 35, 32],
       [33, 20, 33]])